import { readFileSync } from 'node:fs'
import { chmod, mkdir, readFile, rename, rm, stat, writeFile } from 'node:fs/promises'
import path from 'node:path'
import { chromium, type Browser, type BrowserContext, type Page } from 'playwright-core'
import type { CookieEntrySummary, CookieFileView, CookieManagerStatus, CookiePlatform, PlatformCookieStatus } from '../shared/types'

type BrowserCookie = { name: string; value: string; domain: string; path: string; expires: number; httpOnly: boolean; secure: boolean }
type PlatformConfig = { label: string; homeUrl: string; loginUrl: string; domains: string[]; authCookies: string[] }

const LOGIN_TIMEOUT_MS = Number(process.env.SVD_PLATFORM_LOGIN_TIMEOUT_MS || 10 * 60 * 1000)
const PLATFORMS: Record<CookiePlatform, PlatformConfig> = {
  youtube: {
    label: 'YouTube', homeUrl: 'https://www.youtube.com/',
    loginUrl: 'https://accounts.google.com/ServiceLogin?service=youtube&continue=https%3A%2F%2Fwww.youtube.com%2F',
    domains: ['youtube.com'], authCookies: ['SID', 'SAPISID', '__Secure-1PSID', '__Secure-3PSID'],
  },
  instagram: {
    label: 'Instagram', homeUrl: 'https://www.instagram.com/', loginUrl: 'https://www.instagram.com/accounts/login/',
    domains: ['instagram.com'], authCookies: ['sessionid'],
  },
}

function loadBrowserToken(mode: 'container' | 'host') {
  if (mode !== 'host') return ''
  if (process.env.SVD_BROWSER_TOKEN) return process.env.SVD_BROWSER_TOKEN
  try { return readFileSync(process.env.SVD_BROWSER_TOKEN_FILE || '/config/local-browser.token', 'utf8').trim() } catch { return '' }
}

function domainMatches(domain: string, expected: string) {
  const normalized = domain.replace(/^#HttpOnly_/, '').replace(/^\./, '').toLowerCase()
  return normalized === expected || normalized.endsWith(`.${expected}`)
}

function platformForDomain(domain: string): CookiePlatform | 'other' {
  for (const [platform, config] of Object.entries(PLATFORMS) as [CookiePlatform, PlatformConfig][]) {
    if (config.domains.some(expected => domainMatches(domain, expected))) return platform
  }
  return 'other'
}

export function hasPlatformLogin(platform: CookiePlatform, cookies: Pick<BrowserCookie, 'name'>[]) {
  return PLATFORMS[platform].authCookies.some(name => cookies.some(cookie => cookie.name === name))
}

function cookieField(value: string) {
  if (/[\t\r\n]/.test(value)) throw new Error('Cookie 字段包含不支持的制表符或换行')
  return value
}

export function serializeNetscapeCookies(cookies: BrowserCookie[]) {
  const rows = cookies.slice()
    .sort((left, right) => `${left.domain}\t${left.path}\t${left.name}`.localeCompare(`${right.domain}\t${right.path}\t${right.name}`))
    .map(cookie => {
      const domain = `${cookie.httpOnly ? '#HttpOnly_' : ''}${cookieField(cookie.domain)}`
      const includeSubdomains = cookie.domain.startsWith('.') ? 'TRUE' : 'FALSE'
      const expires = cookie.expires > 0 ? Math.floor(cookie.expires) : 0
      return [domain, includeSubdomains, cookieField(cookie.path || '/'), cookie.secure ? 'TRUE' : 'FALSE', expires, cookieField(cookie.name), cookieField(cookie.value)].join('\t')
    })
  return ['# Netscape HTTP Cookie File', '# Generated by Social Video Workbench. Keep this file private.', '', ...rows, ''].join('\n')
}

export function parseNetscapeCookies(contents: string): BrowserCookie[] {
  const cookies: BrowserCookie[] = []
  for (const rawLine of contents.split(/\r?\n/)) {
    const line = rawLine.trim()
    if (!line || (line.startsWith('#') && !line.startsWith('#HttpOnly_'))) continue
    const parts = line.split('\t')
    if (parts.length < 7) continue
    const rawDomain = parts[0], httpOnly = rawDomain.startsWith('#HttpOnly_'), domain = rawDomain.replace(/^#HttpOnly_/, '')
    const expires = Number(parts[4])
    if (!domain || !parts[5]) continue
    cookies.push({ domain, path: parts[2] || '/', secure: parts[3].toUpperCase() === 'TRUE', expires: Number.isFinite(expires) ? expires : 0, name: parts[5], value: parts.slice(6).join('\t'), httpOnly })
  }
  return cookies
}

function validatePlatformCookies(platform: CookiePlatform, cookies: BrowserCookie[]) {
  const config = PLATFORMS[platform]
  const filtered = cookies.filter(cookie => config.domains.some(domain => domainMatches(cookie.domain, domain)))
  if (!filtered.length) throw new Error(`没有找到 ${config.label} 域名的 Cookie`)
  return filtered
}

export function parseManualCookies(platform: CookiePlatform, input: string): BrowserCookie[] {
  const text = input.trim()
  if (!text) throw new Error('请粘贴 Cookie 内容')
  if (text.startsWith('[')) {
    let raw: unknown
    try { raw = JSON.parse(text) } catch { throw new Error('Cookie JSON 格式无效') }
    if (!Array.isArray(raw)) throw new Error('Cookie JSON 必须是数组')
    const cookies = raw.flatMap<BrowserCookie>(item => {
      if (!item || typeof item !== 'object') return []
      const value = item as Record<string, unknown>
      if (!value.name || value.value === undefined || !value.domain) return []
      return [{ name: String(value.name), value: String(value.value), domain: String(value.domain), path: String(value.path || '/'), expires: Number(value.expirationDate || value.expires || 0), secure: Boolean(value.secure), httpOnly: Boolean(value.httpOnly) }]
    })
    return validatePlatformCookies(platform, cookies)
  }
  const netscape = parseNetscapeCookies(text)
  if (netscape.length) return validatePlatformCookies(platform, netscape)
  const domain = `.${PLATFORMS[platform].domains[0]}`
  const header = text.replace(/^cookie\s*:\s*/i, '')
  const cookies = header.split(';').flatMap<BrowserCookie>(part => {
    const separator = part.indexOf('=')
    if (separator <= 0) return []
    return [{ name: part.slice(0, separator).trim(), value: part.slice(separator + 1).trim(), domain, path: '/', expires: 0, secure: true, httpOnly: false }]
  })
  return validatePlatformCookies(platform, cookies)
}

function mergePlatformCookies(existing: BrowserCookie[], platform: CookiePlatform, replacement: BrowserCookie[]) {
  const domains = PLATFORMS[platform].domains
  return [...existing.filter(cookie => !domains.some(domain => domainMatches(cookie.domain, domain))), ...replacement]
}

async function browserCookies(context: BrowserContext, page: Page, platform: CookiePlatform): Promise<BrowserCookie[]> {
  const session = await context.newCDPSession(page)
  try {
    const result = await session.send('Network.getAllCookies')
    const domains = PLATFORMS[platform].domains
    return result.cookies.filter(cookie => domains.some(domain => domainMatches(cookie.domain, domain)))
      .map(cookie => ({ name: cookie.name, value: cookie.value, domain: cookie.domain, path: cookie.path, expires: cookie.expires, httpOnly: cookie.httpOnly, secure: cookie.secure }))
  } finally { await session.detach().catch(() => undefined) }
}

const idleStatus = (platform: CookiePlatform): PlatformCookieStatus => ({ status: 'idle', running: false, message: `尚未保存 ${PLATFORMS[platform].label} Cookie` })

export class YoutubeCookieService {
  private browser?: Browser
  private runningPlatform?: CookiePlatform
  private browserMode: 'container' | 'host' = process.env.SVD_BROWSER_MODE === 'host' ? 'host' : 'container'
  private browserUrl = process.env.SVD_BROWSER_CDP || 'http://browser:9222'
  private browserToken = loadBrowserToken(this.browserMode)
  private cookieFile = process.env.SVD_COOKIES_FILE || '/config/cookies.txt'
  private initialized = false
  private current: CookieManagerStatus = { platforms: { youtube: idleStatus('youtube'), instagram: idleStatus('instagram') } }

  async status() {
    if (!this.initialized) {
      await this.refreshStatus()
      this.initialized = true
    }
    return this.current
  }

  async update(platform: CookiePlatform) {
    this.assertPlatform(platform)
    await this.status()
    if (this.runningPlatform) return this.current
    this.runningPlatform = platform
    const label = PLATFORMS[platform].label
    this.current.runningPlatform = platform
    this.current.platforms[platform] = { status: 'opening', running: true, message: this.browserMode === 'host' ? `正在当前本地浏览器中打开 ${label}…` : `正在远程浏览器中打开 ${label}…` }
    void this.run(platform).catch(error => {
      this.current.platforms[platform] = { status: 'error', running: false, message: error instanceof Error ? error.message : String(error) }
    }).finally(() => { this.runningPlatform = undefined; this.current.runningPlatform = undefined })
    return this.current
  }

  async manual(platform: CookiePlatform, contents: string) {
    this.assertPlatform(platform)
    if (this.runningPlatform) throw new Error('浏览器 Cookie 更新正在进行，请完成后再手动更新')
    const replacement = parseManualCookies(platform, contents)
    const merged = mergePlatformCookies(await this.readCookies(), platform, replacement)
    await this.writeCookies(merged)
    await this.refreshStatus()
    this.initialized = true
    this.current.platforms[platform].message = `${PLATFORMS[platform].label} Cookie 已手动更新，共 ${replacement.length} 条`
    return this.current
  }

  async view(reveal = false): Promise<CookieFileView> {
    const cookies = await this.readCookies()
    let updatedAt: string | undefined
    try { updatedAt = (await stat(this.cookieFile)).mtime.toISOString() } catch { /* no cookie file */ }
    const entries: CookieEntrySummary[] = cookies.map(cookie => ({ platform: platformForDomain(cookie.domain), domain: cookie.domain, path: cookie.path, name: cookie.name, expires: cookie.expires > 0 ? cookie.expires : undefined, secure: cookie.secure, httpOnly: cookie.httpOnly }))
    return { entries, updatedAt, ...(reveal ? { raw: serializeNetscapeCookies(cookies) } : {}) }
  }

  private assertPlatform(platform: string): asserts platform is CookiePlatform {
    if (!(platform in PLATFORMS)) throw new Error('不支持的 Cookie 平台')
  }

  private async context() {
    if (!this.browser?.isConnected()) {
      this.browser = await chromium.connectOverCDP(this.browserUrl, {
        ...(this.browserToken ? { headers: { authorization: `Bearer ${this.browserToken}` } } : {}), noDefaults: true, timeout: 15_000,
      })
      this.browser.on('disconnected', () => { this.browser = undefined })
    }
    const context = this.browser.contexts()[0]
    if (!context) throw new Error('当前浏览器没有可用的持久会话，请重新启动本地浏览器')
    return context
  }

  private async waitForLogin(context: BrowserContext, page: Page, platform: CookiePlatform) {
    const config = PLATFORMS[platform], existing = await browserCookies(context, page, platform)
    if (hasPlatformLogin(platform, existing)) return existing
    this.current.platforms[platform] = { status: 'waiting_login', running: true, message: `请在已打开的浏览器中登录 ${config.label}，登录完成后将自动保存 Cookie` }
    await page.goto(config.loginUrl, { waitUntil: 'domcontentloaded', timeout: 90_000 })
    const deadline = Date.now() + LOGIN_TIMEOUT_MS
    while (Date.now() < deadline) {
      if (page.isClosed()) throw new Error(`${config.label} 登录页面已关闭，Cookie 更新已停止`)
      const cookies = await browserCookies(context, page, platform)
      if (hasPlatformLogin(platform, cookies)) return cookies
      await page.waitForTimeout(1500)
    }
    throw new Error(`等待 ${config.label} 登录超时，请重新点击更新`)
  }

  private async run(platform: CookiePlatform) {
    const config = PLATFORMS[platform]
    let page: Page | undefined
    try {
      const context = await this.context()
      page = await context.newPage()
      await page.goto(config.homeUrl, { waitUntil: 'domcontentloaded', timeout: 90_000 })
      const cookies = await this.waitForLogin(context, page, platform)
      this.current.platforms[platform] = { status: 'saving', running: true, message: `已检测到 ${config.label} 登录，正在安全保存 Cookie…` }
      const replacement = await browserCookies(context, page, platform)
      if (!hasPlatformLogin(platform, replacement)) throw new Error(`未检测到有效的 ${config.label} 登录 Cookie`)
      const merged = mergePlatformCookies(await this.readCookies(), platform, replacement.length ? replacement : cookies)
      await this.writeCookies(merged)
      await this.refreshStatus()
      this.initialized = true
      this.current.platforms[platform].message = `${config.label} Cookie 已更新，共 ${replacement.length} 条`
    } finally {
      await page?.waitForTimeout(600).catch(() => undefined)
      await page?.close().catch(() => undefined)
    }
  }

  private async readCookies() {
    try { return parseNetscapeCookies(await readFile(this.cookieFile, 'utf8')) } catch { return [] }
  }

  private async writeCookies(cookies: BrowserCookie[]) {
    if (!cookies.length) throw new Error('没有可保存的 Cookie')
    const directory = path.dirname(this.cookieFile), temporary = `${this.cookieFile}.new`
    await mkdir(directory, { recursive: true, mode: 0o700 })
    try {
      await writeFile(temporary, serializeNetscapeCookies(cookies), { encoding: 'utf8', mode: 0o600 })
      await chmod(temporary, 0o600)
      await rename(temporary, this.cookieFile)
    } finally { await rm(temporary, { force: true }).catch(() => undefined) }
    await chmod(this.cookieFile, 0o600)
  }

  private async refreshStatus() {
    const cookies = await this.readCookies()
    let updatedAt: string | undefined
    try { const info = await stat(this.cookieFile); updatedAt = info.mtime.toISOString(); await chmod(this.cookieFile, 0o600) } catch { /* no cookie file */ }
    for (const platform of Object.keys(PLATFORMS) as CookiePlatform[]) {
      const domains = PLATFORMS[platform].domains, count = cookies.filter(cookie => domains.some(domain => domainMatches(cookie.domain, domain))).length
      this.current.platforms[platform] = count
        ? { status: 'ready', running: false, message: `${PLATFORMS[platform].label} Cookie 已保存，共 ${count} 条`, cookieCount: count, updatedAt }
        : idleStatus(platform)
    }
  }
}
